### ISSUE TITLE
Materials Broken in Unity 2020.3.8f1

### ISSUE THREAD

**Issue by Necronaut** [infobeisel/AnyUI#3]
Hi there. This looks like a super cool asset but even importing to an empty project I can't use the demo scenes. Am I forced to use a newer version of Unity?

.../AnyUIRenderTexture... File may be corrupted or was serialized with a newer version of Unity.

![Screenshot (1580)](https://user-images.githubusercontent.com/74708811/119025028-913eba80-b958-11eb-9385-41ac5e13d50d.png)

**Comment by infobeisel** [comment]
Hi @Necronaut,
those should be temporary files, meaning you can delete them (and probably reopen the scene). The editor script should then recreate the files. 
Please confirm if this helped, then i can close this issue : )

**Comment by Fozzie-VR** [comment]
In case it helps, I had the same issue as @Necronaut, and deleting the temporary files causing the console errors and then reopening the demo scene worked for me.
