### ISSUE TITLE
How to use this assets for Unity XR

### ISSUE THREAD

**Issue by vrboss** [infobeisel/AnyUI#4]
Hi, Im new in Unity and I try to use your library for curve canvas UI menu for VR Headset (controllers based on Unity XR)
All in demo scene works good in Game window on PC.
But on real device Ray "see" 3d mesh object, but clicks dont works. What I can to do for fix its problem.
For Canvas Raycast I just adding two components: Graphics Raycaster and Tracked Device Graphic Raycaster and clicks on buttons works.
 For 3d  curved mesh I try to adding Tracked Device Physics Raycaster and use XR rig camera in Any Ui Mesh, but its not working(
Please help me.
This is my test project
https://github.com/vrboss/test_project

**Comment by vrboss** [comment]
im solve the problem, thanks for your library =)

**Comment by duanjj0929** [comment]
@vrboss i meet the same problem, could you share your solution? thank you
